# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BctParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bct_id', models.CharField(max_length=50)),
                ('parcel_num', models.CharField(blank=True, max_length=50)),
                ('owner_type', models.CharField(blank=True, max_length=50)),
                ('street_number', models.CharField(blank=True, max_length=10)),
                ('street_name', models.CharField(blank=True, max_length=10)),
                ('acquired', models.DateField(blank=True, default='2017-10-10')),
                ('grantor', models.CharField(blank=True, max_length=100)),
                ('upland', models.FloatField(blank=True)),
                ('wetland', models.FloatField(blank=True)),
                ('habitat', models.CharField(blank=True, max_length=50)),
                ('narrative', tinymce.models.HTMLField(blank=True, default='type something here')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BrewsterBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', tinymce.models.HTMLField(blank=True, default='intro narrative')),
            ],
        ),
    ]
