# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bctv2_map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bctparcel',
            name='street_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
