# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bctv2_map_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bctpoint',
            old_name='bct_point',
            new_name='geom',
        ),
    ]
