# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bctv2_map_app', '0002_auto_20170526_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bctparcel',
            old_name='bct_poly',
            new_name='geom',
        ),
    ]
