# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 23:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bctv2_map_app', '0003_auto_20170526_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewsterBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', tinymce.models.HTMLField(blank=True, default='intro narrative')),
            ],
        ),
    ]
